<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-09T18:25:04 IST" name="Default suite" finished-at="2021-05-09T18:25:04 IST" duration-ms="169">
    <groups>
    </groups>
    <test started-at="2021-05-09T18:25:04 IST" name="Default test" finished-at="2021-05-09T18:25:04 IST" duration-ms="169">
      <class name="testHospitalSolutions">
        <test-method is-config="true" signature="Visits()[pri:0, instance:testHospitalSolutions@44a664f2]" started-at="2021-05-09T18:25:04 IST" name="Visits" finished-at="2021-05-09T18:25:04 IST" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Visits -->
        <test-method signature="testAllOutsidePatients()[pri:0, instance:testHospitalSolutions@44a664f2]" started-at="2021-05-09T18:25:04 IST" name="testAllOutsidePatients" finished-at="2021-05-09T18:25:04 IST" duration-ms="38" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllOutsidePatients -->
        <test-method signature="testAllPatientsWithMultipleVisit()[pri:0, instance:testHospitalSolutions@44a664f2]" started-at="2021-05-09T18:25:04 IST" name="testAllPatientsWithMultipleVisit" finished-at="2021-05-09T18:25:04 IST" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllPatientsWithMultipleVisit -->
        <test-method signature="testLocalPatientsWithMultipleVisit()[pri:0, instance:testHospitalSolutions@44a664f2]" started-at="2021-05-09T18:25:04 IST" name="testLocalPatientsWithMultipleVisit" finished-at="2021-05-09T18:25:04 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLocalPatientsWithMultipleVisit -->
        <test-method signature="testPatientsWithOneVisit()[pri:0, instance:testHospitalSolutions@44a664f2]" started-at="2021-05-09T18:25:04 IST" name="testPatientsWithOneVisit" finished-at="2021-05-09T18:25:04 IST" duration-ms="10" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [100.0] but found [33.33]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [100.0] but found [33.33]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:701)
at org.testng.Assert.assertEquals(Assert.java:712)
at testHospitalSolutions.testPatientsWithOneVisit(testHospitalSolutions.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPatientsWithOneVisit -->
        <test-method signature="testWithZeroPatientRecord()[pri:0, instance:testHospitalSolutions@44a664f2]" started-at="2021-05-09T18:25:04 IST" name="testWithZeroPatientRecord" finished-at="2021-05-09T18:25:04 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWithZeroPatientRecord -->
      </class> <!-- testHospitalSolutions -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
